trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'ajeetraina/scout-demo-voting-app-result'

stages:
- stage: Build
  jobs:
  - job: DockerBuild
    steps:
    - checkout: self
    
    - script: |
        echo "Logging into Docker registry"
        docker login -u ajeetraina -p $(DOCKER_PAT)
      displayName: 'Login to Docker registry'
      
    - script: |
        echo "Building and pushing Docker image"
        docker build -t $(IMAGE_NAME):$BUILD_BUILDNUMBER ./vote
        docker push $(IMAGE_NAME):$BUILD_BUILDNUMBER
      displayName: 'Build and push Docker image'
      
    - script: |
        echo "Analyzing for critical and high CVEs"
        docker run --rm docker/scout-action:latest cves $(IMAGE_NAME):$BUILD_BUILDNUMBER
      displayName: 'Analyze for critical and high CVEs'
      
    - script: |
        echo "Installing Docker Scout"
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin
      displayName: 'Install Docker Scout'
      
    - script: |
        echo "Scouting Docker image"
        docker-scout cves $(IMAGE_NAME):$BUILD_BUILDNUMBER --exit-code --only-severity critical,high
      displayName: 'Scout Docker image with Docker Scout'
