trigger:
- main

pr:
- '*'

stages:
- stage: Build
  jobs:
  - job: BuildServices
    displayName: 'Build and Scan Services'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: UseNode@2
        inputs:
          versionSpec: '14.x'
          checkLatest: true
          installationPath: $(Agent.ToolsDirectory)/node

      - script: echo Building and scanning services...
        displayName: 'Build and Scan Services'

      - script: |
          npm install -g @docker/scout-cli
          docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PAT)
        displayName: 'Setup and Login'

      - script: |
          docker build --pull -t $(DOCKER_HUB_USER)/vote:$(Build.SourceBranchName) ./vote
          docker push $(DOCKER_HUB_USER)/vote:$(Build.SourceBranchName)
          docker scout cves $(DOCKER_HUB_USER)/vote:$(Build.SourceBranchName) --exit-code --only-severity critical,high
        displayName: 'Build, Push, and Scan Vote Service'

      - script: |
          docker build --pull -t $(DOCKER_HUB_USER)/worker:$(Build.SourceBranchName) ./worker
          docker push $(DOCKER_HUB_USER)/worker:$(Build.SourceBranchName)
          docker scout cves $(DOCKER_HUB_USER)/worker:$(Build.SourceBranchName) --exit-code --only-severity critical,high
        displayName: 'Build, Push, and Scan Worker Service'

      - script: |
          docker build --pull -t $(DOCKER_HUB_USER)/result:$(Build.SourceBranchName) ./result
          docker push $(DOCKER_HUB_USER)/result:$(Build.SourceBranchName)
          docker scout cves $(DOCKER_HUB_USER)/result:$(Build.SourceBranchName) --exit-code --only-severity critical,high
        displayName: 'Build, Push, and Scan Result Service'
