# Stage 1: Build the seed data
FROM python:3.9-slim AS builder

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  apache2-utils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /seed

COPY . .

RUN python make-data.py

# Stage 2: Build the runtime image
FROM python:3.9-slim

WORKDIR /seed

COPY --from=builder /seed /seed

ENV AB /usr/bin/ab

CMD /seed/generate-votes.sh
